name: CI Pipeline

on: [push, pull_request]

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Terraform Format
        run: terraform fmt -check
